/**
 * MyAstro
 * API generated with [PHP-CRUD-API](https://github.com/mevdschee/php-crud-api)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/// <reference path="api.d.ts" />

namespace API.Client {
    'use strict';

    export interface InlineResponse2001 {
        "internalId"?: number;

        "id"?: string;

        "kgestionId"?: number;

        "ipAdress"?: string;

        "history"?: string;

        "nom"?: string;

        "prenom"?: string;

        "sexe"?: string;

        "dateNaissance"?: string;

        "signeAstrologique"?: string;

        "conjoint"?: string;

        "email"?: string;

        "tel"?: string;

        "ville"?: string;

        "pays"?: string;

        "questionDate"?: string;

        "questionDate"?: string;

        "questionDateBefore"?: string;

        "questionSujet"?: string;

        "questionContent"?: string;

        "horoscope"?: number;

        "signe2"?: string;

        "partenaires"?: number;

        "dateNaissanceConjoint"?: string;

        "tarot"?: string;

        "tarot1"?: string;

        "numero"?: string;

        "numero1"?: string;

        "voyant"?: string;

        "voyant1"?: string;

        "astro"?: string;

        "astro1"?: string;

        "medium"?: string;

        "medium1"?: string;

        "source"?: string;

        "url"?: string;

        "gclid"?: string;

        "telIsValid"?: number;

        "blacklisted"?: number;

    }

}
